"""Add ticket type visibility

Revision ID: 5afc06344822
Revises: 6084e51e0e55
Create Date: 2026-09-16 15:00:48.170428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5afc06344822'
down_revision: Union[str, Sequence[str], None] = '6084e51e0e55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_types', sa.Column('is_hidden', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_types', 'is_hidden')
    # ### end Alembic commands ###
